name: Deploy Docs

on:
  push:
    branches:
      - main  # 根据您的默认分支名称调整

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 步骤 1：检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 步骤 2：设置 Node.js 环境并缓存 npm 缓存
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # 推荐使用 LTS 版本
          cache: 'npm'

      # 步骤 3：移除现有的 node_modules 和锁定文件
      - name: Remove existing node_modules and lock files
        run: |
          rm -rf node_modules package-lock.json yarn.lock

      # 步骤 4：确保 package-lock.json 存在，如果不存在则安装依赖以生成
      - name: Ensure package-lock.json exists
        run: |
          if [ ! -f package-lock.json ]; then
            echo "package-lock.json not found. Installing dependencies to generate it."
            npm install
          fi

      # 步骤 5：清理 npm 缓存并重新安装依赖
      - name: Clean npm cache and install dependencies
        run: |
          npm cache clean --force
          npm ci

      # 步骤 6：构建 VuePress 文档
      - name: Build Docs with VuePress
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: npm run docs:build

      # 步骤 7：检查 dist 目录是否存在
      - name: Check dist directory
        run: |
          if [ ! -d "src/.vuepress/dist" ]; then
            echo "Dist directory does not exist. Build might have failed."
            exit 1
          else
            echo "Dist directory exists. Proceeding to deploy."
          fi

      # 步骤 8：添加 .nojekyll 文件以防止 Jekyll 处理
      - name: Add .nojekyll file
        run: touch src/.vuepress/dist/.nojekyll

      # 步骤 9：部署到 GitHub Pages
      - name: Deploy Docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: src/.vuepress/dist